### ISSUE TITLE
请问可视化的文件可以分享一下么

### ISSUE THREAD

**Issue by yang654123** [BBBBchan/CorrMatch#6]
我发现文件中没有可视化的代码，作者可以分享一下么

**Comment by BBBBchan** [comment]
感谢您的关注，我们已经上传了correlation map可视化的代码。 您可以在`vis.py`中修改checkpoint和保存路径信息，并运行`vis.sh <gpu num> <port>`进行可视化。

**Comment by 1191067526** [comment]
sh tools/vis.sh 1 12388
/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/hm2023/CorrMatch/vis.py", line 78, in <module>
    for img, mask, ids in valloader:
ValueError: too many values to unpack (expected 3)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 577354) of binary: /home/hm2023/anaconda3/envs/corrmatch/bin/python
Traceback (most recent call last):
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hm2023/anaconda3/envs/corrmatch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
vis.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-07_19:38:35
  host      : ubuntu-Super-Server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 577354)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by hmeng7710** [comment]
首先感谢您的耐心回复，我现在可以正常运行val.sh，但是在运行vis.sh时出现了以下错误：

<img width="600" alt="image" src="https://github.com/BBBBchan/CorrMatch/assets/47852514/29b33b39-663f-41b8-9182-03526a5a968b">

**Comment by BBBBchan** [comment]
> 首先感谢您的耐心回复，我现在可以正常运行val.sh，但是在运行vis.sh时出现了以下错误：
> 
> <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/47852514/320278237-29b33b39-663f-41b8-9182-03526a5a968b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTE1ODQsIm5iZiI6MTcxMjUxMTI4NCwicGF0aCI6Ii80Nzg1MjUxNC8zMjAyNzgyMzctMjliMzNiMzktNjYzZi00MWI4LTkxODItMDM1MjZhNWE5NjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE3MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTA5ZTZiYjJiZGE1ZmE2NzAyYmQ5OTJkZWMwYWYwZWExOTY0NWNkZjViZjU5OWI4ODgyN2MwOWYxNjAxODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SwCi0UbslTVeg-lsRHKWYoNKeckcfa4HozzuCbUifGg">

您好，抱歉对您造成了困扰。
我们已经检查并修复了`vis.py`的代码，具体为：
修改第78行代码`for img, mask, ids in valloader:` 为 `for img, mask, ids, img_ori in valloader:`
您可以使用更新后代码或按照上述描述修改，感谢您的关注。

**Comment by hmeng7710** [comment]
再次感谢您的耐心回复，问题已解决
